// NinjaBox Tarot Deck — 78 kart

export const TAROT_DECK = [
  { id: "ar00", name: "Deli", arcana: "major", image: "ar00.jpg", upright: "Yeni başlangıç, özgürlük, cesaret", reversed: "Dikkatsizlik, plansızlık, riskli adım" },
  { id: "ar01", name: "Büyücü", arcana: "major", image: "ar01.jpg", upright: "İrade, beceri, fırsatları kullanma", reversed: "Manipülasyon, beceriyi yanlış kullanma, gecikme" },
  { id: "ar02", name: "Başrahibe", arcana: "major", image: "ar02.jpg", upright: "Sezgi, sırlar, iç ses", reversed: "Gizli kalanlar, sezgiyi bastırma, belirsizlik" },
  { id: "ar03", name: "İmparatoriçe", arcana: "major", image: "ar03.jpg", upright: "Bereket, sevgi, üretkenlik", reversed: "Duygusal aşırılık, bağımlılık, verimsizlik" },
  { id: "ar04", name: "İmparator", arcana: "major", image: "ar04.jpg", upright: "Düzen, otorite, güven, kontrol", reversed: "Katılık, baskı, kontrolcülük" },
  { id: "ar05", name: "Aziz", arcana: "major", image: "ar05.jpg", upright: "Gelenek, öğreti, bağlılık, rehberlik", reversed: "Dogma, kurallara karşı gelme, katılık" },
  { id: "ar06", name: "Aşıklar", arcana: "major", image: "ar06.jpg", upright: "Aşk, uyum, seçim, güçlü bağ", reversed: "Uyumsuzluk, kararsızlık, yanlış seçim" },
  { id: "ar07", name: "Savaş Arabası", arcana: "major", image: "ar07.jpg", upright: "İlerleme, zafer, kararlılık", reversed: "Kontrol kaybı, yönsüzlük, engeller" },
  { id: "ar08", name: "Güç", arcana: "major", image: "ar08.jpg", upright: "Cesaret, sabır, özdenetim", reversed: "Güvensizlik, öfke, kontrolsüzlük" },
  { id: "ar09", name: "Ermiş", arcana: "major", image: "ar09.jpg", upright: "İçe dönüş, bilgelik, yalnızlık", reversed: "İzolasyon, kapanma, yönünü kaybetme" },
  { id: "ar10", name: "Kader Çarkı", arcana: "major", image: "ar10.jpg", upright: "Değişim, dönüm noktası, fırsat", reversed: "Belirsizlik, gecikme, kontrol dışı değişim" },
  { id: "ar11", name: "Adalet", arcana: "major", image: "ar11.jpg", upright: "Denge, dürüstlük, sonuçlarla yüzleşme", reversed: "Haksızlık, dengesizlik, sorumluluktan kaçma" },
  { id: "ar12", name: "Asılan Adam", arcana: "major", image: "ar12.jpg", upright: "Bekleme, bakış açısı değişimi, teslimiyet", reversed: "Gereksiz bekleme, direnç, ilerleyememe" },
  { id: "ar13", name: "Ölüm", arcana: "major", image: "ar13.jpg", upright: "Dönüşüm, bitiş, yeni dönem", reversed: "Değişime direnç, kapanmayan geçmiş" },
  { id: "ar14", name: "Denge", arcana: "major", image: "ar14.jpg", upright: "Uyum, sabır, ölçülülük, iyileşme", reversed: "Aşırılık, dengesizlik, sabırsızlık" },
  { id: "ar15", name: "Şeytan", arcana: "major", image: "ar15.jpg", upright: "Bağımlılık, tutku, güçlü çekim, maddi bağ", reversed: "Bağımlılıktan kurtulma, zincirleri kırma" },
  { id: "ar16", name: "Kule", arcana: "major", image: "ar16.jpg", upright: "Ani değişim, gerçeklerin ortaya çıkması, yıkılıp yeniden kurma", reversed: "Değişime direnç, gecikmiş kriz" },
  { id: "ar17", name: "Yıldız", arcana: "major", image: "ar17.jpg", upright: "Umut, iyileşme, ilham, olumlu gelecek", reversed: "Umutsuzluk, hayal kırıklığı, güven kaybı" },
  { id: "ar18", name: "Ay", arcana: "major", image: "ar18.jpg", upright: "Belirsizlik, sezgi, korkular, gizli durumlar", reversed: "Sislerin dağılması, gerçeği görme, korkularla yüzleşme" },
  { id: "ar19", name: "Güneş", arcana: "major", image: "ar19.jpg", upright: "Başarı, mutluluk, açıklık, canlılık", reversed: "Geçici gölgelenme, gecikmiş mutluluk" },
  { id: "ar20", name: "Mahkeme", arcana: "major", image: "ar20.jpg", upright: "Uyanış, karar, geçmişi değerlendirme, ikinci şans", reversed: "Kararsızlık, geçmişe takılma, çağrıyı duymama" },
  { id: "ar21", name: "Dünya", arcana: "major", image: "ar21.jpg", upright: "Tamamlanma, başarı, döngünün kapanması", reversed: "Eksik kapanış, gecikme, tamamlanmamış iş" },

  { id: "wa01", name: "Değnek Ası", arcana: "wands", image: "wa01.jpg", upright: "Yeni başlangıç, ilham, tutku", reversed: "Enerji düşüşü, gecikmiş başlangıç" },
  { id: "wa02", name: "Değnek İkilisi", arcana: "wands", image: "wa02.jpg", upright: "Plan, gelecek, seçim", reversed: "Kararsızlık, dar görüş" },
  { id: "wa03", name: "Değnek Üçlüsü", arcana: "wands", image: "wa03.jpg", upright: "Genişleme, ilerleme, beklenen haber", reversed: "Gecikme, sınırlı ilerleme" },
  { id: "wa04", name: "Değnek Dörtlüsü", arcana: "wands", image: "wa04.jpg", upright: "Kutlama, huzur, ev, istikrar", reversed: "Gerilim, istikrarsızlık, gecikmiş kutlama" },
  { id: "wa05", name: "Değnek Beşlisi", arcana: "wands", image: "wa05.jpg", upright: "Rekabet, mücadele, tartışma", reversed: "Çatışmadan kaçınma, bastırılmış gerilim" },
  { id: "wa06", name: "Değnek Altılısı", arcana: "wands", image: "wa06.jpg", upright: "Zafer, takdir, başarı", reversed: "Egonun öne çıkması, takdir eksikliği" },
  { id: "wa07", name: "Değnek Yedilisi", arcana: "wands", image: "wa07.jpg", upright: "Savunma, kararlılık, sınır koyma", reversed: "Yorgunluk, pes etme, baskı altında kalma" },
  { id: "wa08", name: "Değnek Sekizlisi", arcana: "wands", image: "wa08.jpg", upright: "Hız, haber, hareket, gelişme", reversed: "Gecikme, iletişim aksaması" },
  { id: "wa09", name: "Değnek Dokuzlusu", arcana: "wands", image: "wa09.jpg", upright: "Dayanıklılık, son bir çaba, temkin", reversed: "Tükenmişlik, aşırı savunma" },
  { id: "wa10", name: "Değnek Onlusu", arcana: "wands", image: "wa10.jpg", upright: "Yük, sorumluluk, yoğunluk", reversed: "Yükü bırakma, aşırı yüklenme" },
  { id: "wa11", name: "Değnek Prensi", arcana: "wands", image: "wa11.jpg", upright: "Merak, haber, macera, heyecan", reversed: "Sabırsızlık, acelecilik, haber gecikmesi" },
  { id: "wa12", name: "Değnek Şövalyesi", arcana: "wands", image: "wa12.jpg", upright: "Tutku, hareket, cesur adım", reversed: "Dürtüsellik, istikrarsızlık" },
  { id: "wa13", name: "Değnek Kraliçesi", arcana: "wands", image: "wa13.jpg", upright: "Özgüven, çekicilik, bağımsızlık", reversed: "Kıskançlık, güvensizlik, baskınlık" },
  { id: "wa14", name: "Değnek Kralı", arcana: "wands", image: "wa14.jpg", upright: "Liderlik, vizyon, girişim", reversed: "Otoriterlik, acele karar, kibir" },

  { id: "cu01", name: "Kupa Ası", arcana: "cups", image: "cu01.jpg", upright: "Yeni aşk, duygusal başlangıç, sevgi", reversed: "Duygusal tıkanma, kapanmış kalp" },
  { id: "cu02", name: "Kupa İkilisi", arcana: "cups", image: "cu02.jpg", upright: "Karşılıklı sevgi, birliktelik, uyum", reversed: "Ayrılık, uyumsuzluk, karşılıksızlık" },
  { id: "cu03", name: "Kupa Üçlüsü", arcana: "cups", image: "cu03.jpg", upright: "Kutlama, arkadaşlık, mutluluk", reversed: "Aşırılık, üçüncü kişi, yüzeysellik" },
  { id: "cu04", name: "Kupa Dörtlüsü", arcana: "cups", image: "cu04.jpg", upright: "İçe kapanma, ilgisizlik, fırsatı görememe", reversed: "Yeni fırsatı fark etme, yeniden açılma" },
  { id: "cu05", name: "Kupa Beşlisi", arcana: "cups", image: "cu05.jpg", upright: "Kayıp, pişmanlık, üzüntü", reversed: "Kabullenme, iyileşme, geride bırakma" },
  { id: "cu06", name: "Kupa Altılısı", arcana: "cups", image: "cu06.jpg", upright: "Geçmiş, nostalji, eski aşk", reversed: "Geçmişe takılma, geçmişten kopamama" },
  { id: "cu07", name: "Kupa Yedilisi", arcana: "cups", image: "cu07.jpg", upright: "Seçenekler, hayaller, kafa karışıklığı", reversed: "Netleşme, gerçekçi seçim" },
  { id: "cu08", name: "Kupa Sekizlisi", arcana: "cups", image: "cu08.jpg", upright: "Uzaklaşma, bırakma, yeni yol", reversed: "Geri dönme, bırakamama" },
  { id: "cu09", name: "Kupa Dokuzlusu", arcana: "cups", image: "cu09.jpg", upright: "Dilek, memnuniyet, keyif", reversed: "Tatminsizlik, aşırılık" },
  { id: "cu10", name: "Kupa Onlusu", arcana: "cups", image: "cu10.jpg", upright: "Aile, mutluluk, duygusal tamamlanma", reversed: "Aile gerilimi, hayal kırıklığı" },
  { id: "cu11", name: "Kupa Prensi", arcana: "cups", image: "cu11.jpg", upright: "Romantik haber, hassasiyet, teklif", reversed: "Duygusal olgunlaşmamışlık, hayalperestlik" },
  { id: "cu12", name: "Kupa Şövalyesi", arcana: "cups", image: "cu12.jpg", upright: "Romantik yaklaşım, teklif, duygusal hareket", reversed: "Tutarsızlık, hayalcilik, sözde kalma" },
  { id: "cu13", name: "Kupa Kraliçesi", arcana: "cups", image: "cu13.jpg", upright: "Sezgi, şefkat, derin duygular", reversed: "Aşırı hassasiyet, duygusal bağımlılık" },
  { id: "cu14", name: "Kupa Kralı", arcana: "cups", image: "cu14.jpg", upright: "Duygusal olgunluk, denge, sakinlik", reversed: "Duyguları bastırma, manipülasyon" },

  { id: "sw01", name: "Kılıç Ası", arcana: "swords", image: "sw01.jpg", upright: "Gerçek, netlik, karar, yeni fikir", reversed: "Kararsızlık, bulanıklık, yanlış iletişim" },
  { id: "sw02", name: "Kılıç İkilisi", arcana: "swords", image: "sw02.jpg", upright: "Kararsızlık, bekleme, iki seçenek", reversed: "Gerçeği kabul etme, karar verme" },
  { id: "sw03", name: "Kılıç Üçlüsü", arcana: "swords", image: "sw03.jpg", upright: "Kalp kırıklığı, ayrılık, acı", reversed: "İyileşme, affetme, acıyı geride bırakma" },
  { id: "sw04", name: "Kılıç Dörtlüsü", arcana: "swords", image: "sw04.jpg", upright: "Dinlenme, geri çekilme, toparlanma", reversed: "Huzursuzluk, dinlenememe" },
  { id: "sw05", name: "Kılıç Beşlisi", arcana: "swords", image: "sw05.jpg", upright: "Çatışma, gerilim, kazanırken kaybetme", reversed: "Barışma, çatışmayı bırakma" },
  { id: "sw06", name: "Kılıç Altılısı", arcana: "swords", image: "sw06.jpg", upright: "Geçiş, uzaklaşma, daha sakin dönem", reversed: "Geçmişe dönme, ilerlemekte zorlanma" },
  { id: "sw07", name: "Kılıç Yedilisi", arcana: "swords", image: "sw07.jpg", upright: "Gizlilik, strateji, kaçamak davranış", reversed: "Gerçeğin ortaya çıkması, itiraf" },
  { id: "sw08", name: "Kılıç Sekizlisi", arcana: "swords", image: "sw08.jpg", upright: "Kısıtlanma, korku, zihinsel engel", reversed: "Özgürleşme, bakış açısının değişmesi" },
  { id: "sw09", name: "Kılıç Dokuzlusu", arcana: "swords", image: "sw09.jpg", upright: "Kaygı, korku, uykusuzluk", reversed: "Rahatlama, korkuların azalması" },
  { id: "sw10", name: "Kılıç Onlusu", arcana: "swords", image: "sw10.jpg", upright: "Acı veren son, kapanış, dip nokta", reversed: "Toparlanma, yeni başlangıç" },
  { id: "sw11", name: "Kılıç Prensi", arcana: "swords", image: "sw11.jpg", upright: "Merak, haber, gözlem, hızlı zihin", reversed: "Dedikodu, acele söz, düşünmeden hareket" },
  { id: "sw12", name: "Kılıç Şövalyesi", arcana: "swords", image: "sw12.jpg", upright: "Hızlı karar, mücadele, doğrudan hareket", reversed: "Dürtüsellik, saldırganlık, acele" },
  { id: "sw13", name: "Kılıç Kraliçesi", arcana: "swords", image: "sw13.jpg", upright: "Netlik, bağımsızlık, dürüstlük", reversed: "Soğukluk, sertlik, kırıcı tutum" },
  { id: "sw14", name: "Kılıç Kralı", arcana: "swords", image: "sw14.jpg", upright: "Akıl, otorite, strateji, adalet", reversed: "Katılık, manipülasyon, aşırı kontrol" },

  { id: "pe01", name: "Tılsım Ası", arcana: "pentacles", image: "pe01.jpg", upright: "Maddi fırsat, yeni iş, sağlam başlangıç", reversed: "Kaçırılan fırsat, maddi gecikme" },
  { id: "pe02", name: "Tılsım İkilisi", arcana: "pentacles", image: "pe02.jpg", upright: "Denge, uyum sağlama, birden fazla işi yürütme", reversed: "Dengesizlik, yük altında kalma" },
  { id: "pe03", name: "Tılsım Üçlüsü", arcana: "pentacles", image: "pe03.jpg", upright: "İşbirliği, beceri, emek, başarı", reversed: "Ekip sorunu, düşük kalite" },
  { id: "pe04", name: "Tılsım Dörtlüsü", arcana: "pentacles", image: "pe04.jpg", upright: "Güvenlik, birikim, sahip olduklarını koruma", reversed: "Aşırı tutuculuk, bırakmakta zorlanma" },
  { id: "pe05", name: "Tılsım Beşlisi", arcana: "pentacles", image: "pe05.jpg", upright: "Maddi sıkıntı, yalnızlık, destek ihtiyacı", reversed: "Toparlanma, destek bulma" },
  { id: "pe06", name: "Tılsım Altılısı", arcana: "pentacles", image: "pe06.jpg", upright: "Yardım, paylaşım, maddi destek", reversed: "Dengesiz alışveriş, karşılık bekleme" },
  { id: "pe07", name: "Tılsım Yedilisi", arcana: "pentacles", image: "pe07.jpg", upright: "Sabır, yatırım, sonuçları bekleme", reversed: "Sabırsızlık, emeğin karşılığını sorgulama" },
  { id: "pe08", name: "Tılsım Sekizlisi", arcana: "pentacles", image: "pe08.jpg", upright: "Çalışma, ustalık, öğrenme, disiplin", reversed: "Tekdüzelik, motivasyon kaybı" },
  { id: "pe09", name: "Tılsım Dokuzlusu", arcana: "pentacles", image: "pe09.jpg", upright: "Bağımsızlık, refah, emeğin karşılığı", reversed: "Yalnız başarı, aşırı maddiyat" },
  { id: "pe10", name: "Tılsım Onlusu", arcana: "pentacles", image: "pe10.jpg", upright: "Aile, kalıcı başarı, miras, güvence", reversed: "Aile/maddi gerilim, istikrarsızlık" },
  { id: "pe11", name: "Tılsım Prensi", arcana: "pentacles", image: "pe11.jpg", upright: "Yeni iş/fırsat, öğrenme, somut adım", reversed: "Erteleme, motivasyon eksikliği" },
  { id: "pe12", name: "Tılsım Şövalyesi", arcana: "pentacles", image: "pe12.jpg", upright: "Sabır, güvenilirlik, düzenli ilerleme", reversed: "Ağır ilerleme, rutine saplanma" },
  { id: "pe13", name: "Tılsım Kraliçesi", arcana: "pentacles", image: "pe13.jpg", upright: "Güven, bereket, pratiklik, şefkat", reversed: "Aşırı kontrol, maddi kaygı" },
  { id: "pe14", name: "Tılsım Kralı", arcana: "pentacles", image: "pe14.jpg", upright: "Maddi güç, istikrar, başarı, güven", reversed: "Açgözlülük, maddiyatçılık, katılık" }
];

export default TAROT_DECK;
